apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
spec:
  destination:
    name: ''
    namespace: kcd-demo
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/demo-app
    repoURL: 'https://github.com/shaekhhasanshoron/kcd-workshop-gitops-argocd.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background